<?php
use \app\models\helpers\DateConverter;

$actualDateTime = DateConverter::getNow();
$counter = 13;


return [
    'ValidatedUser' => [
        'id' => '1',
        'firstname' => 'Test',
        'lastname' => 'Tester',
        'email' => 'test@ttkv-harburg.de',
        'password' => '$2y$10$FsTab.0ditGEZrY5QK.nL.M4wwROhNbUKEVFC8nNrmww2KPCjR7BC',
        'created' => $actualDateTime,
        'role_id' => '1',
        'vereins_id' => '27',
        'is_validated' => '1',
        'validationtoken' => null,
        'lastlogindate' => null,
        'token' => null,
        'passwordforgottentoken' => null,
        'passwordforgottendate' => null,
        'locked' => null,
        'lockeddate' => null,
    ],
    'UnvalidatedUser' => [
        'id' => '2',
        'firstname' => 'UnTest',
        'lastname' => 'UnTester',
        'email' => 'untest@googlemail.com',
        'password' => '$2y$10$HDJt2gN0PBa6LADaxbqJZOMRuxGTIA5sVuUA8.aAV9LZPH2zqruqK',
        'created' => $actualDateTime,
        'role_id' => '1',
        'vereins_id' => '27',
        'is_validated' => '0',
        'validationtoken' => 'BfH2FR3JIdWW2qBfzFxEQbXjT6yQeuWk',
        'lastlogindate' => null,
        'token' => null,
        'passwordforgottentoken' => null,
        'passwordforgottendate' => null,
        'locked' => null,
        'lockeddate' => null,
    ],
    'ResetPasswordUser' => [
        'id' => '3',
        'firstname' => 'ResetPasswortTest',
        'lastname' => 'ResetPasswortTest',
        'email' => 'resetpassword@ttkv-harburg.de',
        'password' => '$2y$10$HDJt2gN0PBa6LADaxbqJZOMRuxGTIA5sVuUA8.aAV9LZPH2zqruqK',
        'created' => $actualDateTime,
        'role_id' => '1',
        'vereins_id' => '27',
        'is_validated' => '1',
        'validationtoken' => null,
        'lastlogindate' => null,
        'token' => null,
        'passwordforgottentoken' => 'BfH2FR3JIdWW2qBfzFxEQbXjT6yQeuWkoooo',
        'passwordforgottendate' => $actualDateTime,
        'locked' => null,
        'lockeddate' => null,
    ],
    'ResetPasswordUserExpired' => [
        'id' => '4',
        'firstname' => 'ResetPasswortTestExpired',
        'lastname' => 'ResetPasswortTestExpired',
        'email' => 'resetpasswordexpired@ttkv-harburg.de',
        'password' => '$2y$10$HDJt2gN0PBa6LADaxbqJZOMRuxGTIA5sVuUA8.aAV9LZPH2zqruqK',
        'created' => $actualDateTime,
        'role_id' => '1',
        'vereins_id' => '27',
        'is_validated' => '1',
        'validationtoken' => null,
        'lastlogindate' => null,
        'token' => null,
        'passwordforgottentoken' => 'BfH2FR3JIdWW2qBfzFxEQbXjT6yQeuWkooooexpired',
        'passwordforgottendate' => '2022-01-01 15:00:00',
        'locked' => null,
        'lockeddate' => null,
    ],
    'AdminUser' => [
        'id' => '5',
        'firstname' => 'Admin',
        'lastname' => 'Admin',
        'email' => 'admin@ttkv-harburg.de',
        'password' => '$2y$10$bNyOi9GtYMeWeLLS5VWP1O34qiBbtj7ihOeKNeca9vgQIIUdBra5i',
        'created' => $actualDateTime,
        'role_id' => '2',
        'vereins_id' => '27',
        'is_validated' => '1',
        'validationtoken' => null,
        'lastlogindate' => null,
        'token' => null,
        'passwordforgottentoken' => null,
        'passwordforgottendate' => null,
        'locked' => null,
        'lockeddate' => null,
    ],
    'EditVereinUser' => [
        'id' => '6',
        'firstname' => 'EditVerein',
        'lastname' => 'EditVerein',
        'email' => 'editverein@ttkv-harburg.de',
        'password' => '$2y$10$FsTab.0ditGEZrY5QK.nL.M4wwROhNbUKEVFC8nNrmww2KPCjR7BC',
        'created' => $actualDateTime,
        'role_id' => '1',
        'vereins_id' => '27',
        'is_validated' => '1',
        'validationtoken' => null,
        'lastlogindate' => null,
        'token' => null,
        'passwordforgottentoken' => null,
        'passwordforgottendate' => null,
        'locked' => null,
        'lockeddate' => null,
    ],
    'StandardUser' => [
        'id' => '7',
        'firstname' => 'Test',
        'lastname' => 'Tester',
        'email' => 'standard@googlemail.com',
        'password' => '$2y$10$FsTab.0ditGEZrY5QK.nL.M4wwROhNbUKEVFC8nNrmww2KPCjR7BC',
        'created' => $actualDateTime,
        'role_id' => '1',
        'vereins_id' => '27',
        'is_validated' => '1',
        'validationtoken' => null,
        'lastlogindate' => null,
        'token' => null,
        'passwordforgottentoken' => null,
        'passwordforgottendate' => null,
        'locked' => null,
        'lockeddate' => null,
    ],
    'LoginUser' => [
        'id' => '8',
        'firstname' => 'LoginTest',
        'lastname' => 'LoginTest',
        'email' => 'login@ttkv-harburg.de',
        'password' => '$2y$10$bNyOi9GtYMeWeLLS5VWP1O34qiBbtj7ihOeKNeca9vgQIIUdBra5i',
        'created' => $actualDateTime,
        'role_id' => '1',
        'vereins_id' => '27',
        'is_validated' => '1',
        'validationtoken' => null,
        'lastlogindate' => null,
        'token' => null,
        'passwordforgottentoken' => null,
        'passwordforgottendate' => null,
        'locked' => null,
        'lockeddate' => null,
    ],
    'LoginLockedUser' => [
        'id' => '9',
        'firstname' => 'LockedLoginTest',
        'lastname' => 'LockedLoginTest',
        'email' => 'locked@ttkv-harburg.de',
        'password' => '$2y$10$bNyOi9GtYMeWeLLS5VWP1O34qiBbtj7ihOeKNeca9vgQIIUdBra5i',
        'created' => $actualDateTime,
        'role_id' => '1',
        'vereins_id' => '27',
        'is_validated' => '1',
        'validationtoken' => null,
        'lastlogindate' => null,
        'token' => null,
        'passwordforgottentoken' => null,
        'passwordforgottendate' => null,
        'locked' => '1',
        'lockeddate' => $actualDateTime,
    ],
    'LoginUnvalidatedUser' => [
        'id' => '10',
        'firstname' => 'UnvalidatetLoginTest',
        'lastname' => 'UnvalidatetLoginTest',
        'email' => 'unvalidated@ttkv-harburg.de',
        'password' => '$2y$10$bNyOi9GtYMeWeLLS5VWP1O34qiBbtj7ihOeKNeca9vgQIIUdBra5i',
        'created' => $actualDateTime,
        'role_id' => '1',
        'vereins_id' => '27',
        'is_validated' => '1',
        'validationtoken' => null,
        'lastlogindate' => null,
        'token' => null,
        'passwordforgottentoken' => null,
        'passwordforgottendate' => null,
        'locked' => '1',
        'lockeddate' => $actualDateTime,
    ],
    'MydataUser' => [
        'id' => '11',
        'firstname' => 'Mydata',
        'lastname' => 'Mydata',
        'email' => 'mydata@ttkv-harburg.de',
        'password' => '$2y$10$bNyOi9GtYMeWeLLS5VWP1O34qiBbtj7ihOeKNeca9vgQIIUdBra5i',
        'created' => $actualDateTime,
        'role_id' => '1',
        'vereins_id' => '27',
        'is_validated' => '1',
        'validationtoken' => null,
        'lastlogindate' => null,
        'token' => null,
        'passwordforgottentoken' => null,
        'passwordforgottendate' => null,
        'locked' => null,
        'lockeddate' => null,
    ],
    Page\Acceptance\user\VereinsmeldeUserTestdata::getUser(),
    Page\Acceptance\user\EditdataUserTestdata::getUser()
    
];